### ISSUE TITLE
Recent error reports

### ISSUE THREAD

**Issue by havwm9rk** [justas-d/roll20-enhancement-suite#187]
Tried to remove by reference but couldn't find object! function c(){window.r20es.isLoading=!1}
Context
https://app.roll20.net/editor/#
Stack Trace
WebsiteBootstrap.js:18 (o)
WebsiteBootstrap.js:18 (t.removeByReference)
WebsiteBootstrap.js:18 (e.off)
WebsiteBootstrap.js:18 (e.removeEventListener)
WebsiteBootstrap.js:18 (anonymous function)
WebsiteBootstrap.js:1 (n)
WebsiteBootstrap.js:1 (anonymous function)
WebsiteBootstrap.js:1 (anonymous function)

**Comment by PurpleTentacle81** [comment]
I have the same problem. I use VTT 1.15.39 in Opera 73.0.3856.415.

Not every functionality is broken. For example, the Alternative Token Radial Menu works fine, but the tab for exporting a character is missing.
A friend of mine in Firefox 86.0.1 with the same VTT version doesn't see the "Stack Trace" quoted above, but otherwise the problem is the same.

**Comment by justas-d** [comment]
See https://github.com/justas-d/roll20-enhancement-suite/issues/186
